USE ReactaCore;

-- SP_LISTAR_ESTADO --
CREATE OR ALTER PROC SP_LISTAR_ESTADO
AS
BEGIN
    SELECT *
    FROM Estados
END
GO

-- SP_INSERTAR_ESTADO --
CREATE OR ALTER PROC SP_INSERTAR_ESTADO
@NombreEstado VARCHAR(50)
AS
BEGIN
  BEGIN TRY
    BEGIN TRAN
      INSERT INTO Estados VALUES (@NombreEstado)
    COMMIT
    PRINT 'ESTADO INSERTADO'
  END TRY
  BEGIN CATCH
    ROLLBACK
    PRINT 'ERROR AL INSERTAR ESTADO ' + CAST(ERROR_NUMBER() AS VARCHAR)
  END CATCH
END
GO


-- SP_EDITAR_ESTADO --
CREATE OR ALTER PROC SP_EDITAR_ESTADO
@EstadoId INT,@NombreEstado VARCHAR(50)
AS
BEGIN
  BEGIN TRY
    BEGIN TRAN
      UPDATE Estados SET NombreEstado=@NombreEstado WHERE EstadoId=@EstadoId
    COMMIT
    PRINT 'ESTADO EDITADO'
  END TRY
  BEGIN CATCH
    ROLLBACK
    PRINT 'ERROR AL EDITAR ESTADO'
  END CATCH
END
GO


-- SP_ELIMINAR_ESTADO --
CREATE OR ALTER PROC SP_ELIMINAR_ESTADO
@EstadoId INT
AS
BEGIN
  BEGIN TRY
    BEGIN TRAN
      DELETE Estados WHERE EstadoId=@EstadoId
    COMMIT
    PRINT 'ESTADO ELIMINADO'
  END TRY
  BEGIN CATCH
    ROLLBACK
    PRINT 'ERROR AL ELIMINAR ESTADO'
  END CATCH
END
GO


-- SP_BUSCAR_ESTADO_POR_ID --
CREATE OR ALTER PROC SP_BUSCAR_ESTADO_POR_ID
(
    @EstadoId INT
)
AS
BEGIN
    SELECT 
        EstadoId,
        NombreEstado
    FROM Estados
    WHERE EstadoId = @EstadoId;
END
GO


-- SP_FILTRAR_ESTADO --
CREATE OR ALTER PROC SP_FILTRAR_ESTADO
(
    @NombreEstado VARCHAR(50) = NULL
)
AS
BEGIN
    SELECT 
        EstadoId,
        NombreEstado
    FROM Estados
    WHERE (@NombreEstado IS NULL 
           OR NombreEstado LIKE '%' + @NombreEstado + '%');
END
GO








